### ISSUE TITLE
Extract testing infrastructure and release as testing module

### ISSUE THREAD

**Issue by vanniktech** [firebase/geofire-java#101]
I think if we put some effort into the testing infrastructure we could pull it out into it's own module and ship it. The big benefits are that consumers of the library can actually do integration testing of their firebase database and geoquery data.

**Comment by samtstern** [comment]
Huh that's not a bad idea.  So the idea would be to release a set of geofire test utils as a library?

**Comment by vanniktech** [comment]
Yup. The idea is a bit taken from oktthp. They've got their OkHttp lib in one and then they provide you with a MockWebServer that can be used for testing.

We'd probably ship the `RealDataTest` class in a way that it's customizable and can be used for talking to the firebase database. Also some of the testing event listeners and the `SimpleFuture`.

**Comment by vanniktech** [comment]
This would be ready for my side now and we could cut a 2.3.0 version.

**Comment by samtstern** [comment]
@vanniktech so want me to release current `master` to `2.3.0`?

**Comment by vanniktech** [comment]
I think it would make sense as the feature is nice and others could use it. Unless you have anything else you'd want to be in 2.3.0.

**Comment by samtstern** [comment]
@vanniktech give it a spin and let me know!

**Comment by vanniktech** [comment]
Will do so on Monday. Thanks for the cut.

**Comment by vanniktech** [comment]
Unfortunately I have to postpone this a bit but I'll keep playing around with it and come up with possible improvements if necessary.
