### ISSUE TITLE
Switch from maven to Gradle

### ISSUE THREAD

**Issue by vanniktech** [firebase/geofire-java#102]
Gradle is the new build system and it's far more customizable. Also, it would probably ease releasing new models.

Is there any reason this wasn't converted?

**Comment by samtstern** [comment]
No reason, and since I bet most of our usage is on Android not Java this probably makes sense.  It would certainly make some things easier.

**Comment by samtstern** [comment]
One thing to note here is we use the "maven release plugin" for releases which I like.  I am not aware of a Gradle replacement, although I am sure it exists.

**Comment by vanniktech** [comment]
We can use the [maven gradle plugin](https://github.com/vanniktech/Emoji/blob/master/gradle/gradle-mvn-push.gradle).

**Comment by vanniktech** [comment]
What's the take on this one? Should we make the switch or leave everything as is? How are usually firebase projects being distributed?

**Comment by samtstern** [comment]
@vanniktech I am in favor of leaving this one as-is since nothing has really broken with gradle yet (#82 is being fixed by the play services people soon).

**Comment by vanniktech** [comment]
Works for me. Then I'll close this.
