### ISSUE TITLE
Allow unit tests to run on PRs

### ISSUE THREAD

**Issue by samtstern** [firebase/geofire-java#106]
Right now when a PR comes in we skip all tests because the `RealDataTest` and some other integration tests require service account credentials.

We should let unit tests run.

**Comment by vanniktech** [comment]
Yes totally agree. Can we open source the firebase testing project and commit the json file? That way everyone will be able to run the tests.

**Comment by vanniktech** [comment]
We could encrypt this and inject it the same way the credentials for uploading artifacts use that travis feature.

**Comment by samtstern** [comment]
We do encrypt and upload the service account key, however encrypted files are not available on PR builds because that's a security risk.  Otherwise you could send us a PR with a `build.sh` that just says "once decrypted, print out the service account" which would expose the encrypted data to anyone who opens a PR.

**Comment by vanniktech** [comment]
Huh interesting. Didn't know that. So how can we run unit tests?

**Comment by samtstern** [comment]
I assume we just need to do a fancy `mvn test` invocation that filters out the integration tests and runs the rest.

**Comment by vanniktech** [comment]
Hmmm but that wouldn't have caught the recent regression. With Gradle it'd be easy to filter things out. We need it more and more.

**Comment by samtstern** [comment]
Well running the `testCompile` phase would have caught the most recent regression, and we now run that on PRs as well.
