### ISSUE TITLE
org.apache.httpcomponents and httpclient warning

### ISSUE THREAD

**Issue by ersin-ertan** [firebase/geofire-java#13]
Getting this warning:
Warning:Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages

Solved via:
```java
compile 'com.firebase:firebase-client-android:2.3.1'
compile ('com.firebase:geofire:1.1.0'){
	exclude group: 'org.apache.httpcomponents', module: 'httpclient'
}
```
Does this justify a documentation change in the readme/projects?

**Comment by jdimond** [comment]
It seems you have tied the dependency to 1.1.0. Can you check whether it still exists with 1.1.1, the current version, for which we tweaked the sub-dependencies a bit.

**Comment by ersin-ertan** [comment]
This is no longer a problem in 1.1.1. Thanks.

**Comment by Mohamed-mekawy** [comment]
yup , same problem and solved via 
compile 'com.firebase:geofire:1.1.1+'
thanks @jdimond and @ersin-ertan for sharing the problem
