### ISSUE TITLE
Why GeoFire's GeoQuery's queryAtLocation not returning keys eventhough the lat & long within the given KMs?

### ISSUE THREAD

**Issue by RageshAntony** [firebase/geofire-java#130]
I am creating an Android App , an Uber Clone. In this I am using Firebase to list the rides created by the user.

The Ride stored in the following format .
```

{
  "category" : "NUVO",
  "driverids" : "",
  "drop_lat" : "40.7127753",
  "drop_long" : "-74.0059728",
  "estdate" : "Wed@Feb@28th",
  "estmile" : "4.19",
  "esttime" : "01:02@PM",
  "esttotalfare" : "4.61",
  "fareest" : "1.1",
  "g" : "t9z83wv46x",
  "l" : [ 40.674426, -73.944033 ],
  "notes" : "Gv",
  "orgin_lat" : "145 Brooklyn Ave, Brooklyn, NY 11213, USA%20New York, NY, USA",
  "request_id" : "5a75579740d166e95b8b4567",
  "requested_category" : "FAM_SUV",
  "rider_id" : "5a507bf340d16660288b4567",
  "status" : 1,
  "trip_id" : 0
}
```
Now I am Using GeoFire's GeoQuery's queryAtLocation to pick all rides with in 5 KMs from his current location.

The query uses the lat & lang from the field "l" and compare it with the current location lat & lang of the driver.

If the list's lat & lang is within 5 KMs , it will return the key , that is the parent name of the child "l".

Now I am currently in India. I use Lockito App to fix a Mock GPS location in India. After that I create a Ride within 5 KMs radius.

Now , the ride successfully listed in the drivers list. No Problem.

**My Issue**

But When I fix a mock GPS location in USA , this flow not working. I fixed the driver location on Brookyln Childeren's Museum and also created a ride on the same museum. But GeoQuery not calling onKeyEntered . It simply exists after calling GeoQueryReady function .

I check my current Lat & Lang from the app and it returns as 40.67434763453142,-73.94402358680964. I checked this against the lat&lang on field "l" .(refer above JSON). Both pointing to same location.

But GeoQuery failed to retrieve it

My Question Why this issue happening ?. If I use India's locations. Geoquery works perfectly .

But why it failing in USA.

You may tell ,"There will be an issue in lockito". But Lockito returning correct location lat lang . I checked it in Logcat. And , if there is a issue in Lockitto then How it working in India.

Also , I check it with other countries. There also I get this issue. Except my Home country , No other places are working 

**Here My GeoQoery Code :**
```

 try {
            showDialog();
            double nearByDistanceRadius = 5.00d;

            com.firebase.geofire.GeoFire geoFire = new com.firebase.geofire.GeoFire(FirebaseDatabase.getInstance().getReference().child(childtype));
            final com.firebase.geofire.GeoQuery geoQuery = geoFire.queryAtLocation(new GeoLocation(latitude, longitude), nearByDistanceRadius);
            geoQueryEventListener=new GeoQueryEventListener() {
                @Override
                public void onKeyEntered(final String key, GeoLocation location) {
                    Toast.makeText (getApplicationContext(), "The key is = ",Toast.LENGTH_LONG).show();
                }

                @Override
                public void onKeyExited(final String key) {
                    System.out.println("ON KEYEXITED"+key);
                }

                @Override
                public void onKeyMoved(String key, GeoLocation location) {
                    System.out.println("ON KEYMOVED"+key);
                }

                @Override
                public void onGeoQueryReady() {
                    System.out.println("ON KEYQUERYREADY");


                @Override
                public void onGeoQueryError(DatabaseError error) {
                    System.out.println("ON KEYERROR"+error);
                }
            };
            geoQuery.addGeoQueryEventListener(geoQueryEventListener);

        } catch (Exception e) {
            e.printStackTrace();
        }
```
Above , execpt onGeoQueryReady , no method called if I use outside India. But Working in India. Please help me with this issue.

**Comment by puf** [comment]
Cross-posted on: https://stackoverflow.com/questions/48595274/why-geofires-geoquerys-queryatlocation-not-returning-keys-eventhough-the-lat

**Comment by samtstern** [comment]
@RageshAntony the best way to see if this is an error in your app code or in the library would be to try adding a test case to the `GeoQueryIT` class like this one:
https://github.com/firebase/geofire-java/blob/master/java/src/test/java/com/firebase/geofire/GeoQueryIT.java#L30

If you're not comfortable doing that, please provide:
  * The lat long of a few locations you expect to get in your query
  * The lat long of the query center
  * Radius

**Comment by samtstern** [comment]
@RageshAntony it's been a while since your last response so going to close this issue.
