### ISSUE TITLE
GeoLocation() has private access int <mypackagenamehere>

### ISSUE THREAD

**Issue by mudebbela** [firebase/geofire-java#131]
Hey I'm really unsure how much of an issue this is supposed to be but im get that error in my code. Why might this be the case. Also this is my first time dropping an error here so feel free to ask for me to elaborate if necessary.

**Comment by samtstern** [comment]
@mudebbela could you show the code that causes this error?

**Comment by mudebbela** [comment]
private void queryGeolocation(double longitude, double latitude) {
        GeoQuery geoQuery = geoFire.queryAtLocation(new GeoLocation(longitude, latitude), 0.6);
    }



So that's the exact snippet of code. Assume everything else works. I copied it exactly from the example shown on here so it should work as far as I can tell. I'm getting the error lines under the "new GeoLocation(longitude, latitude)" constructor. so maybe the creators of GeoLocation() changed the way the constructor works within the last 25 days.

**Comment by samtstern** [comment]
@mudebbela can you copy-and-paste your exact error message?

Also is it possible you have your own class called `GeoLocation` with a private constructor?

**Comment by mudebbela** [comment]
Hey sorry for the delay, it turned out yes I had my own class called GeoLocation, I'm a little novice at this so that is totally my fault
