### ISSUE TITLE
How to know the number of locations exists in geofire?

### ISSUE THREAD

**Issue by skhizerabass** [firebase/geofire-java#132]
Is there anyway to know or any event that will let me know, If there is no location in that particular area.
What i mean is if i want to check the locations under some lat lng. And if there isn't any location existed near to that lat lng I want to display that no Locations exists at that place.

Thanks 
Regards

**Comment by sanisloandras** [comment]
Hi.
I'm not a GeoFire expert, but I think that You should implement this logic using the GeoQueryEventListener.
You should collect your data into a list in onKeyEntered(String key, GeoLocation location) method of the GeoQueryEventListener, until onGeoQueryReady() is fired. Once the onGeoQueryReady is fired, You can check if your list is empty or not.

And You should also listen to further onKeyEntered, onKeyRemoved events, since data can change and You can get real-time updates.

`boolean mIsGeoQueryReady = false;
        List<Object> mData = new ArrayList<>();
        geoQuery.addGeoQueryDataEventListener(new GeoQueryDataEventListener() {
            @Override
            public void onDataEntered(DataSnapshot dataSnapshot, GeoLocation location) {
                if (!mIsGeoQueryReady) {
                    mData.add(dataSnapshot);
                }
            }

            @Override
            public void onDataChanged(DataSnapshot dataSnapshot, GeoLocation location) {
                Log.d(TAG, "onDataChanged: " + dataSnapshot.getKey() +
                        " / " + dataSnapshot.getValue() + " " + location);
            }

            @Override
            public void onGeoQueryReady() {
                mIsGeoQueryReady = true;
                Log.d(TAG, "onGeoQueryReady: " + mData.isEmpty());
            }
        });`

**Comment by samtstern** [comment]
Thanks @sanisloandras for chiming in.

@skhizerabass firebase does not support any kind of "count" query so there's no way to just check for the count that a `GeoQuery` will return.  But the suggestion above is right, you can do this by issuing the query, counting what comes in, and wait for the initial "ready" signal.

**Comment by skhizerabass** [comment]
@sanisloandras  Thanks bro! I think it will solve my issue that is what i want.

**Comment by sanisloandras** [comment]
@samedson Don'y You actually think that it would be nice if the onGeoQueryReady() method had this data out of the box? It's really easy to implement(I think/hope) and it might be usefull often.

**Comment by vanniktech** [comment]
I'm personally against that.

**Comment by Tukajo** [comment]
I don't think it makes sense to be including count into a regular query as it bloats the payload with irrelevant information that can easily just be calculated manually if necessary.

**Comment by skhizerabass** [comment]
I personally don't think that we should have a count method. Because we can already get what we want in Ready method.
@sanisloandras Your method worked like a charm for me
