### ISSUE TITLE
2.3.1 version crashes on geoFire.removeLocation

### ISSUE THREAD

**Issue by emailsubjekt** [firebase/geofire-java#149]
Self explanatory. Gradle 3.1.1 wrapper 4.10.1, version 28, all newest firebase libraries. Known problem. Just wondering when this is going to be solved?

**Comment by samtstern** [comment]
@emailsubjekt when you say "Known Problem" can you point to an existing issue you think is the same?

**Comment by emailsubjekt** [comment]
I am referring to this 
https://stackoverflow.com/questions/49029529/is-geofire-version-2-3-0-incompatible-with-play-service-location-version-11-8-0
this
https://stackoverflow.com/questions/50687405/geofire-setlocation-not-working
and this 
https://stackoverflow.com/questions/48930447/geofire-error-with-setlocation

In my case it's removeLocation() - I will not go check out your docs

**Comment by emailsubjekt** [comment]
Also most importantly this link
https://github.com/firebase/geofire-java/issues/28

**Comment by emailsubjekt** [comment]
Some seem to advise that all you need is a completion listener, so I've just made it, updated to 2.3.1 and about to try it. However some say even with a completion listener it still crashes..? I am about to try it, will write back. 

Also another solution from that last link #28, from umarhussain15 is to use his library alongside yours I'm guessing unless this is an official version ->  https://github.com/umarhussain15/geofire-android ? 

Please respond, I've been waiting for months for you guys to update, is there a solution for this.

**Comment by emailsubjekt** [comment]
It seems to work now that I've added a completion listener 

       try {
                                            if (!(geoFire == null)) {
                                                geoFire.removeLocation(location_name, new GeoFire.CompletionListener() {
                                                    @Override
                                                    public void onComplete(String key, DatabaseError error) {
                                                        if (error != null) {
                                                            System.err.println("There was an error removing the location from GeoFire: " + error);
                                          
                                                        } else {
                                                            System.out.println("Location removed on server successfully!");
                                          
                                                        }
                                                    }
                                                });      
                                            }
                                        } catch (Exception e) {
                                            e.printStackTrace(); 
                                        }


However, your official instructions here https://github.com/firebase/geofire-java state that a completion listener is not necessary ->"To remove a location and delete it from the database simply pass the location's key to removeLocation: geoFire.removeLocation("firebase-hq");"

Can you please elaborate on this?

**Comment by emailsubjekt** [comment]
And a day has passed and not elaboration on this whatsoever. Great job guys.

**Comment by samtstern** [comment]
This should be fixed in version `3.0.0` which separates `geofire-java` from `geofire-android` completely.

P.S. Please be more respectful with your comments in the future.  Derisive or sarcastic comments don't do anything to speed up the development process.
