### ISSUE TITLE
Possible to remove radius size and fetch all locations?

### ISSUE THREAD

**Issue by hamzabinamin** [firebase/geofire-java#150]
I noticed that the max radius size is 8587 km. It doesn't search higher than this number. Is it possible to remove the radius restriction completely and fetch all the coordinates?

**Comment by samtstern** [comment]
When you create your `GeoFire` reference you use code like this:
```
DatabaseReference ref = FirebaseDatabase.getInstance().getReference("path/to/geofire");
GeoFire geoFire = new GeoFire(ref);
```

If you want to get *all* locations, just access all of the data at `ref`.  There's no way to do this directly in GeoFire though, you'll need to read the data yourself.
