### ISSUE TITLE
Could not resolve: `com.firebase:geofire-java:3.0.0`

### ISSUE THREAD

**Issue by wakandan** [firebase/geofire-java#159]
searching online shows https://mvnrepository.com/artifact/com.firebase/geofire-java/2.3.0 is the latest version of geofire-java. Is there something wrong here?

**Comment by samtstern** [comment]
@wakandan recent builds of geofire are hosted on jCenter rather than Maven Central.

The URL is https://jcenter.bintray.com/ so https://jcenter.bintray.com/com/firebase/geofire-java/
