### ISSUE TITLE
onKeyEntered() method called many times as number of locations I haved

### ISSUE THREAD

**Issue by Qadomy** [firebase/geofire-java#160]
When I run the app the onKeyEntered() method called a number times as the number of locations I have, until without the current location reaches the GeoFire location,

My code:

     for (final Location location: locationsArea){

            // Add circles for locations
            mMap.addCircle(new CircleOptions()
                    .center(location.getLocationPoistion())
                    .radius(GEOFENCE_RADIUS)
                    .strokeColor(Color.argb(50, 70, 70, 70))
                    .fillColor(Color.argb(100, 150, 150, 150))
                    .strokeWidth(5.0f)
            );

            // set markers for locations
            mMap.addMarker(new MarkerOptions()
                    .position(location.getLocationPoistion())
                    .title(location.getLocationName())
                    .icon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_ORANGE))
                    .snippet("Click here to more info.")

            );

            // create a GeoQuery when user reach a location in dangerousArea
            GeoQuery geoQuery = geofire.queryAtLocation(new GeoLocation(location.getLocationPoistion().latitude,
                    location.getLocationPoistion().longitude), GEOFENCE_RADIUS);

            final String locationName = location.getLocationName();
            geoQuery.addGeoQueryEventListener(new GeoQueryEventListener() {
                @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
                @Override
                public void onKeyEntered(String key, GeoLocation location) {
                    Log.d(tag, "onKeyEntered");

                    sendNotification(NOTIFICATION_TITLE, String.format("%s are entered "+locationName, key));
                }

                @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
                @Override
                public void onKeyExited(String key) {
                    Log.d(tag, "onKeyExited");

                    sendNotification(NOTIFICATION_TITLE, String.format("%s are leaving "+locationName, key));

                }

                @Override
                public void onKeyMoved(String key, GeoLocation location) {
                    Log.d(tag, "onKeyMoved");

                    //sendNotification("Qadomy", String.format("%s are moving within the "+locationName, key));

                }

                @Override
                public void onGeoQueryReady() {
                    Log.d(tag, "onGeoQueryReady");

                }

                @Override
                public void onGeoQueryError(DatabaseError error) {
                    Log.d(tag, "onGeoQueryError");

                    Toast.makeText(MapsActivity2.this, error.getMessage(), Toast.LENGTH_SHORT).show();
                }

            });
        }

**Comment by Qadomy** [comment]
this for loop inside onMapReady()

**Comment by samtstern** [comment]
@Qadomy it's normal for `onKeyEntered` to be called once per key.  This is the expected behavior of the library and it's similar to how RTDB child event listeners work.  If you want to know when it's all done, wait for `onGeoQueryReady`
