### ISSUE TITLE
Geoquery not working when i set the radius below 4.9

### ISSUE THREAD

**Issue by ChoLianJiet** [firebase/geofire-java#161]
What i wanted to achieve was to fetch nearby keys which are within 0.6km, and populate markers the all the keys which entered the area, code as below:-

    private void initializeGeoQuery() {
        Log.d(TAG, "My location is " + mMyLocation.getLatitude() + "," + mMyLocation.getLongitude());
        mGeoQuery = mGeoFire.queryAtLocation(new GeoLocation(mMyLocation.getLatitude(), mMyLocation.getLongitude()), 0.6);
        mGeoQuery.addGeoQueryEventListener(new GeoQueryEventListener() {
            @Override
            public void onKeyEntered(final String key, final GeoLocation location) {
                if (!key.equals(mMyUserName)) {
                    Log.d(TAG, key + " has entered the area at " + location.latitude + "," + location.longitude + ".");
                    if (!otherUsersMarkersMap.containsKey(key)) {
                        Log.d(TAG, "Adding " + key + " to map");
                        updateOtherMarkers(key, "onKeyEntered");
                    }
                }
            }

            @Override
            public void onKeyExited(final String key) {
                if (!key.equals(mMyUserName)) {
                    Log.d(TAG, key + " has exited the area.");
                    updateOtherMarkers(key, "onKeyExited");
                }
            }

            @Override
            public void onKeyMoved(String key, GeoLocation location) {
                Log.d(TAG, "Map is " + otherUsersMarkersMap);
                if (!key.equals(mMyUserName)) {
                    Log.d(TAG, key + " has moved int the area to " + location.latitude + "," + location.longitude + ".");
                    if (otherUsersMarkersMap.containsKey(key)) {
                        updateOtherMarkers(key, "onKeyMoved");
                    }
                }
            }

            @Override
            public void onGeoQueryReady() {
                Log.d(TAG, "GeoQuery is ready!");
            }

            @Override
            public void onGeoQueryError(DatabaseError error) {
                Log.d(TAG, "Error on GeoQuery: " + error);
            }
        });
    }

However, it does not work, but when i set the radius to 4.9 or above it works fine:- 

        mGeoQuery = mGeoFire.queryAtLocation(new GeoLocation(mMyLocation.getLatitude(), mMyLocation.getLongitude()), 4.9);

When, i set the radius to anything 4.8 or below, all the callbacks in the geoquery could not trigger, and i don't understand why.

Hope that anyone can help to solve this issue.

**Comment by samtstern** [comment]
@ChoLianJiet can you give an example of a specific data  point where this fails with a radius of 4.8km?  Specifically can you give me:

- The lat/lng for the center of the query
- The lat/lng of an entry that you expect to be in the results but is not

**Comment by ChoLianJiet** [comment]
Suddenly it seems it works, i think maybe there's some bug in my code yesterday, sorry for the trouble and thank you so much!

**Comment by samtstern** [comment]
Glad it worked and thanks for following up!
