### ISSUE TITLE
Upgrade GeoFire to the 3.x.x Java SDK

### ISSUE THREAD

**Issue by DonaldBough** [firebase/geofire-java#18]
Will GeoFire have to be updated now that firebase has changed some of their structure as well? Could you show the implementation of these changes in the README.md instructions?

Thanks!

**Comment by niiapa** [comment]
Yes please. I realized GeoFire for JS(web) was updated but I couldn't find the updated files for Android. And I've been in a very intensive migrating process. This seems to be the only snag.

**Comment by jwngr** [comment]
@abehaskins is working on getting this updated. Hang tight. We have a lot of different open source libraries across a handful of languages, so it will take us a little while to get everything upgraded and tested. I'll keep this issue open to track this work.

Glad you guys are excited about the new version of the Firebase Java SDK!

**Comment by brunocortes06** [comment]
waiting the new release to continue developing with the new Google firebase SDK...

**Comment by jwngr** [comment]
The existing GeoFire SDK still works with the `2.x.x` Firebase SDKs. We will cut a new release soon, but you are not currently blocked on using GeoFire in any way.

**Comment by brunocortes06** [comment]
I migrated all my code yet to 3.0. Just waiting geofire, my application is In development phase. 

Enviado do meu iPhone

**Comment by gouravd** [comment]
All other migration done. I hope the Geofire migration comes soon & is easy peasy too!

**Comment by CodingAleCR** [comment]
So, just to see if I understood correctly, you can use Geofire with the new Firebase SDK? How??

**Comment by brunocortes06** [comment]
No, you can't. 

Enviado do meu iPhone

**Comment by jwngr** [comment]
See #20 which upgrades the GeoFire for Java library to be compatible with the Firebase `3.x.x` Java SDK.

**Comment by felipezf** [comment]
Hi, do you have some news about this update? Tks!

**Comment by Trunksome** [comment]
really exited for this as well!

**Comment by sosoprime** [comment]
When are we getting the update? I need to launch

**Comment by samtstern** [comment]
#24 has been merged, I am going to work on getting the library published now.  Still no hard timeline as the publishing process has changed and there could be unforeseen issues.

**Comment by samtstern** [comment]
This is now published on jCenter.  Please see `README.md` for more details, there are some changes in how you get the library for the new version.
