### ISSUE TITLE
queryAtLocation is not working

### ISSUE THREAD

**Issue by srinivaasang1** [firebase/geofire-java#19]
The lattitude and longitude is not being returned

GeoFire geoFire1 = new GeoFire(new Firebase("https://....../profile/"));
                GeoQuery geoQuery = geoFire1.queryAtLocation(new GeoLocation(-37.920547, 145.130357), 0.6);
                geoQuery.addGeoQueryEventListener(new GeoQueryEventListener() {
                    @Override
                    public void onKeyEntered(String key, GeoLocation location) {
                        System.out.println(String.format("Key %s entered the search area at [%f,%f]", key, location.latitude, location.longitude));
                    }

                    @Override
                    public void onKeyExited(String key) {
                        System.out.println(String.format("Key %s is no longer in the search area", key));
                    }

                    @Override
                    public void onKeyMoved(String key, GeoLocation location) {
                        System.out.println(String.format("Key %s moved within the search area to [%f,%f]", key, location.latitude, location.longitude));
                    }

                    @Override
                    public void onGeoQueryReady() {
                        System.out.println("All initial data has been loaded and events have been fired!");
                    }

                    @Override
                    public void onGeoQueryError(FirebaseError error) {
                        System.err.println("There was an error with this query: " + error);
                    }
                });

![screen shot 2016-05-22 at 12 07 09 am](https://cloud.githubusercontent.com/assets/11976261/15448864/156b14a8-1fb1-11e6-87d7-37a43b5e8a47.png)

**Comment by jwngr** [comment]
What is being returned? Do you mind providing some sample output? Is it possible just none of the locations are being matched?

**Comment by sosoprime** [comment]
You're setting the geofire wrongly. Set the geolocation at a particular node using different keys.

**Comment by jwngr** [comment]
Yeah it does look like you are mixing regular data with your GeoFire index and not storing all data in the same node. You want to make sure you are keeping all your GeoFire data in the same node, otherwise your geoqueries will not work.
