### ISSUE TITLE
GeoFire

### ISSUE THREAD

**Issue by joemerritt** [firebase/geofire-java#23]
I may be missing something. But has GeoFire been updated to work with the new configuration of Firebase?

**Comment by nasznjoka** [comment]
Not yet Geofire 1.1.0 requires the use of old firebase database implementation... It throws error on Context() and socan not be used.... I'm also waiting for the update

**Comment by joemerritt** [comment]
Yep, driving me crazy... I wonder how many apps are not able to be updated due to this? Do you know of any other solutions?

**Comment by jwngr** [comment]
Dupe of https://github.com/firebase/geofire-java/issues/18.
