### ISSUE TITLE
Could not find com.firebase:geofire:2.0.0

### ISSUE THREAD

**Issue by MostafaAnter** [firebase/geofire-java#32]
Error:Could not find com.firebase:geofire:2.0.0.
Required by:
    MAKOnWay:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by jwngr** [comment]
GeoFire for Java `2.0.0` has not been released yet. Tracked in #24.

**Comment by puf** [comment]
Cross-post: http://stackoverflow.com/questions/38055305/errorcould-not-find-com-firebasegeofire2-0-0
