### ISSUE TITLE
compile 'com.firebase:geofire:2.0.0' missing

### ISSUE THREAD

**Issue by JMieczkowski** [firebase/geofire-java#35]
Hello,

When I try compile 'com.firebase:geofire:2.0.0' it fails to resolves and looking on both maven and jcenter, I only see 1.1.1 as being the lastest.

**Comment by samtstern** [comment]
Sorry about this, we are working on releasing GeoFire on Maven Central.
This is our mistake not yours, right now 2.0.0 exists in this repo but is
not published live.

Sam

**Comment by JMieczkowski** [comment]
Is there an ETA on when 2.0.0 will be released?

**Comment by denabelarde** [comment]
+1

**Comment by longy26** [comment]
+1
would love to see this resolved asap! Thank you =)

**Comment by kgnatiko** [comment]
+1

**Comment by samtstern** [comment]
Ok the libraries are now live on jCenter, working on getting them into Maven Central but you should be able to use them now if you have jCenter in your repositories.

Please see the README and note that `com.firebase:geofire` is no longer the dependency.  Due to how the new SDK works we now have `geofire-java` (for Java server apps) and `geofire-android` (for Android apps).  They have the same API but different underlying dependencies.

**Comment by MostafaAnter** [comment]
i have jCenter but it seem not working 
and give me Error:Could not find com.firebase:geofire:2.0.0.

**Comment by samtstern** [comment]
@MostafaAnter please see my previous comment and also the README.  There is no such thing as `com.firebase:geofire:2.0.0`, you need to choose either `com.firebase:geofire-android:2.0.0`or `com.firebase:geofire-java:2.0.0`

**Comment by cantfindit91** [comment]
not working even if i do 
compile 'com.firebase:geofire-android:2.0.0'
getting:
 Error:Could not find com.firebase:geofire:2.0.0.

**Comment by MostafaAnter** [comment]
yes exactly

**Comment by MostafaAnter** [comment]
yes exactly    not working even if i do 
compile 'com.firebase:geofire-android:2.0.0'
getting:
Error:Could not find com.firebase:geofire:2.0.0.

**Comment by botty87** [comment]
@MostafaAnter add this: maven { url "http://dl.bintray.com/firebase/geofire" }
under repositories in your build.gradle

**Comment by samtstern** [comment]
@MostafaAnter sorry this is my fault, I forgot to turn the parent project live so the error you're seeing is correct.  I just turned it live, it should take a few hours to propagate.  @botty87's workaround will help for now.

**Comment by MostafaAnter** [comment]
i'm waiting and thanx for your interesting :+1:

**Comment by samtstern** [comment]
Should work now!  Just got the email from Bintray that it's all in jcenter and I tried it myself, app compiles without local or `dl.bintray` dependencies.
