### ISSUE TITLE
Displaying GeoQueries in a ListView.

### ISSUE THREAD

**Issue by R00t6** [firebase/geofire-java#36]
I have posted a question on displaying GeoQueries in a ListView. I have implemented a custom FirebaseListAdapter. Why isn't there any Android Example for GeoQueries in a ListView. I am new to Firebase I was using Parse before but now they have shutdown. My applicaton's domain is Geo Location base so please provide us with a GeoFire ListView example and help me solve the issue where I might be wrong. Here is my question on [StackOverFlow.](http://stackoverflow.com/questions/38480284/geofire-listview-query-doesnt-display-text-in-the-listview)

**Comment by samtstern** [comment]
@R00t6 please don't double post issues unless you have two different questions.  I think StackOverflow is a better place for this question since it's not an actual problem with a library, it's a request for implementation help.  I am going to close this issue here and take a look on SO.
