### ISSUE TITLE
Add method to update GeoQuery center and radius together atomically

### ISSUE THREAD

**Issue by joreilly** [firebase/geofire-java#39]
I have been calling GeoQuery setCenter() and setRadius() as user zooms in/out in google maps (in android app) and noticed that that seems to be kicking off parallel sets of firebase queries (they both call setupQueries()).  Should there be single method to set both of these (similar to geoFire.queryAtLocation(() method when initially creating the GeoQuery object)?

**Comment by jwngr** [comment]
Thanks for the suggestion. Sounds like a reasonable proposal. I don't foresee us finding time to do this ourselves in the near future, but we will gladly review a PR if you or someone else wants to put it together.
