### ISSUE TITLE
Reading geo-fire locations in gae does not work

### ISSUE THREAD

**Issue by Rainking80** [firebase/geofire-java#40]
I had a conversation with the firebase support and was asked to put my issue into this channel. He was able to replicate the issue with a condensed code sample of mine. He also said it might be related to [https://github.com/firebase/geofire-java/issues/11](https://github.com/firebase/geofire-java/issues/11).

My situation:
I have a google app engine running with java. I want to read and write locations with my app engine. Writing a location is working quiet well (but callback is not working). When I try to read locations from the firebase database I see an exception in my app engine log. 

This is the exception:

> Uncaught exception from servlet java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup") at ... 

this is my gradle build:

```
dependencies {
    appengineSdk 'com.google.appengine:appengine-java-sdk:1.9.40'
    compile 'com.google.firebase:firebase-server-sdk:[3.0.0,)'
    compile 'javax.servlet:servlet-api:2.5'
    compile 'com.firebase:geofire-java:2.0.0'
    compile 'com.google.appengine:appengine-api-1.0-sdk:1.9.40'
    compile 'org.apache.httpcomponents:httpclient:4.5.2'
}
```

this is the call from my java servlet which throws the exception:

```
DatabaseReference ref = FirebaseDatabase.getInstance().getReference("places/");
GeoFire geoFire = new GeoFire(ref);
geoFire.setLocation("firebase-hq", new GeoLocation(37.7853889, -122.4056973));
//geoFire.removeLocation("firebase-hq");

GeoQuery geoQuery = geoFire.queryAtLocation(new GeoLocation(37.7832, -122.4056), 0.6);

geoQuery.addGeoQueryEventListener(new GeoQueryEventListener() {
    @Override
    public void onKeyEntered(String key, GeoLocation location) {
        System.out.println(String.format("Key %s entered the search area at [%f,%f]", key, location.latitude, location.longitude));
    }

    @Override
    public void onKeyExited(String key) {
        System.out.println(String.format("Key %s is no longer in the search area", key));
    }

    @Override
    public void onKeyMoved(String key, GeoLocation location) {
        System.out.println(String.format("Key %s moved within the search area to [%f,%f]", key, location.latitude, location.longitude));
    }

    @Override
    public void onGeoQueryReady() {
        System.out.println("All initial data has been loaded and events have been fired!");
    }

    @Override
    public void onGeoQueryError(DatabaseError error) {
        System.err.println("There was an error with this query: " + error);
    }
});

```

Comment from firebase-support:

> It appears that this issue only affects geofire-java and not the Firebase SDK per se.

Kind regards,
Tino

**Comment by jwngr** [comment]
@samtstern / @abehaskins / @jdimond - Any thoughts here?

**Comment by samtstern** [comment]
@jwngr @Rainking80 according to the AppEngine docs you can't create new background threads via the normal method:
https://cloud.google.com/appengine/docs/java/runtime?csw=1#threads

We don't do 'new Thread()` anywhere but in `ThreadEventRaiser` we call `Executors.newSingleThreadExecutor()` which I suspect could be the culprit here.

I don't have the background to know what our options are here, maybe @jdimond does?

**Comment by Rainking80** [comment]
I thought background threads in app engine are possible now. Since the standard firebase API (for non geofire data) also uses background threads and is working well. When I read other data from firebase than via geofire API I am queit sure it is using callback functions which use background threads. So I guess its something inside geofire.

**Comment by Rainking80** [comment]
Are there any news for this issue?

**Comment by jonahbron** [comment]
:+1: I am also having issues with this.  If I read a particular location, then try to query by location, I get the same error.

**Comment by jonahbron** [comment]
This bug is a huge issue for my app.  It's depending on the ability to query geo locations from the service.  As of now, it seems like this library is only usable in Android, and not in back-end services at all. :cry: 

What's our path to a solution?

**Comment by jonahbron** [comment]
Done some more research.  It appears that background threads on GAE must be made via the ThreadManager API.

https://cloud.google.com/appengine/docs/java/runtime#background_threads_1

Based on that, it seems like a third `EventRaiser` implementation needs to be created.  Something like `ThreadManagerEventRaiser` or `AppEngineEventRaiser`.

**Comment by jonahbron** [comment]
I created a PR that could possibly fix this issue.

#58

**Comment by jonahbron** [comment]
I'd really like some direction on how to set up development for GeoFire on my machine.  I've spent a bunch of time trying to get it to compile under Android Studio and Intellij, but haven't gotten either working yet.  What kind of setup to the main devs use?

**Comment by jonahbron** [comment]
I even tried to use reflection to modify the raiseEvent behavior, but I can't access the EventRaiser interface to implement it.  I don't think it's possible for me to test this behavior without modifying the library itself.

**Comment by samtstern** [comment]
@jdimond can you comment on this?  I don't know enough about GeoFire or AppEngine internals.

**Comment by jonahbron** [comment]
@Rainking80 If you're interested, a workaround for now seems to be to copy ` src/main/java` directly into the Java package code for your own project.  With the correct AppEngineEventRaiser from #58, I can now successfully query from Google App Engine.

**Comment by vanniktech** [comment]
Is this still happening? Or does the workaround work?

**Comment by vanniktech** [comment]
Should we close this since it's inactive? If we ever run into this again we can create a new issue and put some more effort / dedication into this.

**Comment by Rainking80** [comment]
Hi,
Sorry Unfortunately I could not test it. I switched my backend technology to node.js and mongodb. I could not wait for a solution so long. Best regards, Tino

**Comment by samtstern** [comment]
Thanks @Rainking80 for the response!  Closing for now.
