### ISSUE TITLE
Receiving distance in callback

### ISSUE THREAD

**Issue by jhalborg** [firebase/geofire-java#45]
It would be awesome if the onKeyEntered/move etc. callbacks also included a distance from the query point, as the JS library does. It supports the numerous use cases of "return the 20 closest x (restaurants, gyms, whatever), sorted by how close they are"

[https://github.com/firebase/geofire-js/blob/master/docs/reference.md#geoqueryoneventtype-callback](url)

**Comment by jwngr** [comment]
I agree this is a great idea! We will gladly accept a pull request for this if you'd like to give it a shot. Realistically, we won't be adding this feature any time soon unless it comes from a community contribution. Thanks!

**Comment by vanniktech** [comment]
Can't this be implemented by using the `Location` from the listener and comparing this one to the one that was given into the `setLocation` method?

If so, I'd choose to not have this in the library itself.

**Comment by samtstern** [comment]
@vanniktech you're right and I agree with your assessment.  Given that point and the age of the issue, I will close this.

Thank you @jhalborg for filing this initially.  If you feel strongly about this (after all this time!) we can certainly re-open and continue discussion.
