### ISSUE TITLE
Math error in GeoHashQuery.java cause code to give unexpected exception

### ISSUE THREAD

**Issue by giacomodeglinnocenti** [firebase/geofire-java#46]
Hello, I'm new to submitting issues to GitHub, but this has to be fixed I think.

I was getting mad on trying to figure out why my app was giving me an Exception when I was setting the GeoQuery radius to a big number (>500'000), so I started debugging the code and found what it seems to me to be a math error.

The Exception that I get is :
` java.lang.IllegalArgumentException: Precision of GeoHash must be larger than zero! 
at com.firebase.geofire.core.GeoHash.<init>(GeoHash.java:29)`

The code I try to execute is:
`someGeoQuery.setRadius(500000);
`
The lines that I think are wrong are:  ( in file **com.firebase.geofire.core.GeoHashQuery.java**)
```
        int queryBits = Math.max(1, Utils.bitsForBoundingBox(location, radius));
        int geoHashPrecision = (int)(Math.ceil(queryBits/Base32Utils.BITS_PER_BASE32_CHAR));
```

In fact, queryBits and Base32Utils.BITS_PER_BASE32_CHAR , are both integer, so a division of that kind can only bring to an integer result, so why the need of the ceil?
I think this is an error, and it cause a consequentially wanted Exception.

The code has to be corrected to :
```
        **float** queryBits = Math.max(1, Utils.bitsForBoundingBox(location, radius));
        int geoHashPrecision = (int)(Math.ceil(queryBits/Base32Utils.BITS_PER_BASE32_CHAR));
```

The version that I'm using is:
`   'com.firebase:geofire-android:2.1.0'
`

Am I right?

**Comment by samtstern** [comment]
@giacomodeglinnocenti happy to review a PR if you decide to submit one.

Have you determined exactly how large of a number you need to cause this problem?  Half the earth's circumference is about 20,000km so that's about as far as any two points on earth could be.  Seems like you'd never need a GeoQuery with a radius of 500,000km (but of course it wouldn't hurt for the library to support this!)

**Comment by giacomodeglinnocenti** [comment]
The problems comes out when looking for a radius of 2500 km or larger.

I'm going to push the commit to the master branch.

The change I made is really small, so it should work, however, I was not able to test it. Can you do it or suggest how to do it?

**Comment by samtstern** [comment]
@giacomodeglinnocenti we have tests here: https://github.com/firebase/geofire-java/tree/master/src/test/java/com/firebase/geofire

You could add a unit test for this case and then run `mvn test` to see if it passes.  Of course make sure the tests also pass on your machine **before** you do any changes so you know where you're starting.

**Comment by giacomodeglinnocenti** [comment]
It's giving me error:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] geofire ............................................ SUCCESS [  1.728 s]
[INFO] geofire-android .................................... FAILURE [  4.755 s]
[INFO] geofire-java ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:43 min
[INFO] Finished at: 2016-09-22T17:27:36+02:00
[INFO] Final Memory: 18M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project geofire-android: Could not resolve dependencies for project com.firebase:geofire-android:aar:2.1.1-SNAPSHOT: Failed to collect dependencies at com.google.firebase:firebase-database:aar:[9.0.2,): No versions available for com.google.firebase:firebase-database:aar:[9.0.2,) within specified range -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :geofire-android

Do I have to configure maven repos?

**Comment by samtstern** [comment]
Can you check that your Play Services SDK is up to date:
http://stackoverflow.com/questions/37310188/failed-to-resolve-com-google-firebasefirebase-core9-0-0/37310513#37310513

also make sure that the ANDROID_HOME variable in your environment is set to
the location of your android SDK.  For me it looks like this:

$ echo $ANDROID_HOME
/usr/local/google/home/samstern/android-sdk-linux

**Comment by giacomodeglinnocenti** [comment]
I've the latest Play Services SDK now. 

I've tried to setted the ANDROID_HOME, but I was not knowing which was the right directory so I tried with both of following, I did "mvn clean" too, but it still does not work, same error.

DESKTOP-ELCJTTQ:geofire jack$ ls **$HOME/.android**
adbkey				avd				ddms.cfg			emu-update-last-check.ini	modem-nv-ram-5554		uid.txt
adbkey.pub			breakpad			debug.keystore			extras				modem-nv-ram-5556
analytics.settings		cache				default.keyset			metrics				monitor-workspace
DESKTOP-ELCJTTQ:geofire jack$ ls **/Users/jack/Library/Android/sdk**
SDK Readme.txt	add-ons		build-tools	extras		licenses	platform-tools	platforms	skins		sources		system-images	tools

**Comment by giacomodeglinnocenti** [comment]
I noticed that I don't have **Google Repository** in my SDK Tools. Is this ok?

![schermata 2016-09-22 alle 18 18 12](https://cloud.githubusercontent.com/assets/20744688/18756666/0bca1948-80f1-11e6-9957-a2bbbc0d82fe.png)

**Comment by samtstern** [comment]
@giacomodeglinnocenti hmmm that all looks good to me.  I am surprised it is not working.

Can you do:
```
ls -R $ANDROID_HOME/extras/google/m2repository/com/google/firebase
```

**Comment by giacomodeglinnocenti** [comment]
![schermata 2016-09-22 alle 18 18 12](https://cloud.githubusercontent.com/assets/20744688/18757722/74a6b7c4-80f5-11e6-9bd6-a4dc49978ffb.png)
![schermata 2016-09-22 alle 18 47 43](https://cloud.githubusercontent.com/assets/20744688/18757723/74cd1298-80f5-11e6-85dd-b6212f2484b1.png)
[repos.txt](https://github.com/firebase/geofire-java/files/487870/repos.txt)

No GeoFire repos here?

**Comment by giacomodeglinnocenti** [comment]
It is possible that the setting of envoiroment variables as not been propagated?

I set them with just:
export ANDROID_HOME=/Users/jack/Library/Android/sdk

and not by launchd.conf. I'm on mac.

**Comment by giacomodeglinnocenti** [comment]
Any news on this?

**Comment by samtstern** [comment]
@giacomodeglinnocenti I honestly can't figure out what the difference is between your environment and mine.  I just tried it on a computer where I had never used GeoFire before and after setting `ANDROID_HOME` and putting a `service-account.json` into the `java` directory it worked perfectly.

That said, it's the tests in the `java` directory that actually matter, so you should be able to test this change even though your `android` subproject fails.

Can you proceed writing up your PR?  When testing just do `mvn test -pl java` to avoid the Android bits.

**Comment by giacomodeglinnocenti** [comment]
As I can see today the error seems to be no more there!!! :O

Now I'm just getting a 'service-account.json' missing error. I'll try to solve it tomorrow and proceed with the PR.

**Comment by samtstern** [comment]
Ah cool!  All you need do do for the service account thing is:

 1) Create a Firebase project (mine is called GeoFire test)
 2) Go to the Google Cloud console (not the Firebase console) and locate that same project
 3) Download a Service Account JSON key
 4) Put it at `java/service-account.json`

That should make the tests run.

**Comment by giacomodeglinnocenti** [comment]
👍

**Comment by giacomodeglinnocenti** [comment]
Hello,
 I've successfully launched the test, before the modification, but it is failing due to some timeout.
Do I have to set a timeout variable at any level?

`[...]
  Failed tests:   geoFireSetsLocations(com.firebase.geofire.GeoFireTest): Timeout occured!
  getLocationReturnsCorrectLocation(com.firebase.geofire.GeoFireTest): Timeout occured!
  getLocationOnWrongDataReturnsError(com.firebase.geofire.GeoFireTest): Timeout occured!
  keyMoved(com.firebase.geofire.GeoQueryTest): Timeout occured!
  keyEntered(com.firebase.geofire.GeoQueryTest): Timeout occured!
  keyExited(com.firebase.geofire.GeoQueryTest): Timeout occured!
  subQueryTriggersKeyMoved(com.firebase.geofire.GeoQueryTest): Timeout occured!
  removeSingleObserver(com.firebase.geofire.GeoQueryTest): Timeout occured!
  removeAllObservers(com.firebase.geofire.GeoQueryTest): Timeout occured!
  readyListener(com.firebase.geofire.GeoQueryTest): Timeout occured!
  readyListenerAfterReady(com.firebase.geofire.GeoQueryTest): Timeout occured!
  readyAfterUpdateCriteria(com.firebase.geofire.GeoQueryTest): Timeout occured!

Tests run: 28, Failures: 12, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min
[INFO] Finished at: 2016-09-26T16:47:23+02:00
[INFO] Final Memory: 15M/195M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project geofire-java: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/jack/Documents/Android/geofire/java/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExceptio`

**Comment by samtstern** [comment]
@giacomodeglinnocenti huh that's not something I have seen before.  If you just submit a PR, I can test it for you/

**Comment by giacomodeglinnocenti** [comment]
Hey, sorry, I'm new to GitHub contributes, so I've tried to follow the guide to open a pull request on branch geofire-2 but what I've done is to request the merge of that branch with the master. 

However, if I try to direct commit from my git client to master, I don't have the credentials to do so.

Which branch do I have to commit the changes to?

**Comment by samtstern** [comment]
@giacomodeglinnocenti thanks for being persistent here,  I'll try to explain the easiest way to do a pull request:

  1. Get a clean copy of `geofire-java` (`git clone ...`)
  1. Make yourself a new branch (`git checkout -b my-fix-branch`)
  1. Make your changes and commit them (`git commit -am "Fix radius issue")
  1. Add your fork as a `remote` (`git remote add fork https://github.com/giacomodeglinnocenti/geofire-java`)
  1. Push your new branch to your fork (`git push -u fork my-fix-branch:my-fix-branch`)
  1. In the github UI, create a new pull request from branch `giacomodeglinnocenti/geofire-java/my-fix-branch` to `firebase/geofire-java/master`

**Comment by giacomodeglinnocenti** [comment]
I've done points 1 to 5, but I don't know how to do the point 6. 

![schermata 2016-10-03 alle 21 15 50](https://cloud.githubusercontent.com/assets/20744688/19050450/e8fe14b6-89ae-11e6-8557-44314ed84a78.png)

I can't find the firebase/geofire-java repository from my project pull request screen. 

Are you sure in point 4 that I've to create the fork on `https://github.com/giacomodeglinnocenti/geofire-java` and not on `https://github.com/firebase/geofire-java/` ?

**Comment by samtstern** [comment]
How did you create the repo "https://github.com/giacomodeglinnocenti/geofire-java"? It does not appear to be a "fork" of firebase/geofire-java so that's why Github is not offering you the right choices.

**Comment by giacomodeglinnocenti** [comment]
I've created it manually as a new repository, because on point 5 I've got a "repository not found" error as follow:

`iPhone:geofire jack$ git remote add fork https://github.com/giacomodeglinnocenti/geofire-java
iPhone:geofire jack$ git push -u fork max-radius-fixed-branch:max-raiuds-fixed-branch
Username for 'https://github.com':  *******
Password for 'https://info@giacomodeglinnocenti.com@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/giacomodeglinnocenti/geofire-java/' not found
`

So I created it from the GitHub UI, by selecting "New Repository" and giving it "geofire-java" name.
Do I have to create it by "Import a repository" and so import it from `https://github.com/firebase/geofire-java` ?

**Comment by samtstern** [comment]
Yeah `git remote add` does not create a repo, it just allows you to have a new destination to push and pull to.  The proper way to create a fork is through the Github forking UI.

**Comment by giacomodeglinnocenti** [comment]
Ok, I've done the pull request!

Let me know if it will pass the tests!!! :)
