### ISSUE TITLE
getLocation onChangeListener

### ISSUE THREAD

**Issue by brezinajn** [firebase/geofire-java#55]
Is there a possibility to attach onChangeListener to geoLocation? Sure there is possibility to use for example
```
DatabaseReference ref = FirebaseDatabase.getInstance().getReference(path)
                .child(key)
                .child("l");

ref.addValueEventListener(...
```
but to have this functionality embedded in geofire would be nice.

**Comment by jwngr** [comment]
This already exists and is called `onKeyMoved()`. See the code sample in [this section](https://github.com/firebase/geofire-java#geo-queries) of the `README`.

**Comment by brezinajn** [comment]
Sorry I wasn't really clear. I ment querying single key. I men't something like: 
```
geoFire.getLocation("firebase-hq", new LocationListener() {
...
@Override
public void onKeyMoved(GeoLocation location)
```
That I presume isn't possible.

**Comment by jwngr** [comment]
What is your use case for this? You could just listen to the node which stores the data for the key in question and duplicate the location data there. And, when that data changes (as detected by an `addValueEventListener()`), complete your logic. I don't think re-building that same functionality into GeoFire is worth the effort / added API surface.

**Comment by brezinajn** [comment]
My use case is tracking subset of users (not all users) in the area. I agree there are other ways to achieve it. Thanks for your time.
