### ISSUE TITLE
Add empty Constructor to GeoFire

### ISSUE THREAD

**Issue by leonardo2204** [firebase/geofire-java#60]
If you try to deserialize GeoFire, an error is thrown by Jackson because no default constructor was provided.

**Comment by samtstern** [comment]
Can you explain what you mean by "deserialize GeoFire"?  A short example code snippet would be helpful.

**Comment by leonardo2204** [comment]
Sorry about that, I have GeoFire inside an Address class which is inside a User class.
When I fetch for the user on Firebase, I get a "no default constructor on GeoFire" error.
I think this clarifies the issue: http://stackoverflow.com/questions/41149801/firebase-no-default-constructor-deserialize

Thanks

**Comment by samtstern** [comment]
@leonardo2204 thanks for explaining.  That's currently the expected/desired behavior of this library.  GeoFire data should not be nested within the objects but rather flattened into a sibling tree and keyed on object ID.

See [the documentation](https://firebase.google.com/docs/database/web/structure-data#avoid_nesting_data) on nesting data for some more information.

As @puf said in the StackOverflow post, if you want to store geolocations as nested data you will need to roll your own POJO class.

**Comment by leonardo2204** [comment]
@samtstern Ok then, thank you for the feedback and explaining !
Happy holidays !
