### ISSUE TITLE
onGeoQueryReady never called

### ISSUE THREAD

**Issue by nirvik66** [firebase/geofire-java#61]
Hi

I have a really simple database with 3 location objects:
<img width="297" alt="screen shot 2017-01-03 at 2 35 01 pm" src="https://cloud.githubusercontent.com/assets/4172434/21620351/db71eba0-d1c1-11e6-8852-498d739158ff.png">

My rules are the following:
<img width="566" alt="screen shot 2017-01-03 at 2 36 08 pm" src="https://cloud.githubusercontent.com/assets/4172434/21620376/076b8fea-d1c2-11e6-98e6-354b7699523b.png">

And I'm trying to obtain the bars within a radius. Currently all the bars are within the radius.
onKeyEntered gets called 3 times successfully but the call to onGeoQueryReady in never notified.

```
GeoFire geoFire = new GeoFire(mBarsLocationReference);
        final GeoQuery geoQuery = geoFire.queryAtLocation(new GeoLocation(latitude, longitude), RADIUS_KM);
        geoQuery.addGeoQueryEventListener(new GeoQueryEventListener() {
      .........
}
```

Thanks

**Comment by jwngr** [comment]
Your rules and data look fine, so I assume there is something wrong with the actual code. But from what you've provided, there isn't enough information to tell. What path does `mBarsLocationReference` point to (it should be `/bars_location`)? Does it point to the correct Firebase project (it should be the same one your data is stored in)? And what are the values for `latitude`, `longitude`, and `RADIUS_KM` (if you make them exactly the same as one of your locations stored in the Database with a radius of 100 km, does it fire?)?

**Comment by nirvik66** [comment]
`mBarsLocationReference` is pointing to `bars_location` and I'm passing for example 40.487569808939526 / -3.6884727515280247 as latitude / longitude and a RADIUS_KM value of 10km. This information has to be correct because I do get the notification for the "onKeyEntered" event for the correct bars. The one I'm always missing is the "onGeoQueryReady" notification to know that all my data has been loaded.

**Comment by jwngr** [comment]
Sorry about that, I misread your initial message. Can you share the full code that shows how you attached the `onKeyEntered` and `onGeoQueryReady` listeners? We unfortunately still don't have enough information to help you diagnose what is going wrong.

Also, what version of the SDK are you using? If you aren't using the latest (`2.1.1` as of right now), please try upgrading to make sure this isn't just an issue with an old version of the SDK.

**Comment by nirvik66** [comment]
Working fine with the latest SDK! Sorry, my bad :(

**Comment by samtstern** [comment]
@nirvik66 glad it works!
