### ISSUE TITLE
LocationChangedListener

### ISSUE THREAD

**Issue by kerner1000** [firebase/geofire-java#62]
Hi, thanks for this great library!

I would like to add the following method to GeoFire:

```
public void listenLocation(String key, LocationCallback callback) {
        DatabaseReference keyRef = this.getDatabaseRefForKey(key);
        LocationValueEventListener valueListener = new LocationValueEventListener(callback);
        keyRef.addValueEventListener(valueListener);
    }
```

its a tiny difference to `GeoFire#getLocation(String key, LocationCallback callback)`;

I tried to extend `GeoFire` and add the new method.
Unfortunately `getDatabaseRefForKey()` is package private and `databaseReference` is private. Also, `LocationValueEventListener` is not visible.

Maybe you could add the classical listener method or change some visibilities.
Many thanks!

**Comment by vanniktech** [comment]
You can use the `getDatabaseReference()` method that's public to achieve this.

**Comment by samtstern** [comment]
Thanks @vanniktech
