### ISSUE TITLE
Delay when .onKeyEntered/.onKeyExited is triggered

### ISSUE THREAD

**Issue by sl378** [firebase/geofire-java#64]
I'm trying to use Geofire to achieve geofencing functionality offered by the Google Awareness fence api

However I'm wondering what's the best way to achieve the equivalant of INITIAL_TRIGGER_DWELL flag, so onKeyEntered is triggered when the point of interest is already inside the radius for certain amount of time.

References:
[GeofencingRequest](https://developers.google.com/android/reference/com/google/android/gms/location/GeofencingRequest)
[LocationFence](https://developers.google.com/android/reference/com/google/android/gms/awareness/fence/LocationFence.html#in(double,%20double,%20double,%20long))

**Comment by vanniktech** [comment]
I don't quite understand what you want to achieve but you could delay the events easily by either posting Runnables into Handlers or using somethings that more sophisticated like RxJava.

**Comment by samtstern** [comment]
Yes @vanniktech is correct, this is outside the scope of this library.  If you want to do advanced accounting like this you can either delay the initial query or build a customized listener to do that work.
