### ISSUE TITLE
onKeyEntered() method not getting call even data available

### ISSUE THREAD

**Issue by jondoes** [firebase/geofire-java#65]
When I pass longitude as positive value then it not calling onKeyEntered() method.
It directly call onGeoQueryReady() method even data available in radius.

When I pass longitude as negative value then it is calling onKeyEntered() method.

**Comment by jwngr** [comment]
Can you please put together an [mcve](https://stackoverflow.com/help/mcve) which reproduces this behavior? Most likely, there are just no keys which match the criteria when your longitude is a positive value. Make sure the key you are expecting to see is actually within the bounding circle.
