### ISSUE TITLE
Rx for Geofire

### ISSUE THREAD

**Issue by ahaverty** [firebase/geofire-java#68]
Is there a Rx library for Geofire?
I'd like to be able to concurrently listen to my firebase data and my geofire locations. Would wrapping Geofire in Rx help or is there an alternative?

**Comment by samtstern** [comment]
@ahaverty there is not an Rx library for GeoFire.  I think some people may find it useful for sure, but I don't think we'd ever make it part of the core library.

For that reason going to close this issue, but if you release something of your own please comment here since I'd love to see it.

**Comment by ahaverty** [comment]
Thanks @samtstern will do 👍
