### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by LuisOma** [firebase/geofire-java#69]
When i debug the projetc appear the next errors:

Error:Error: File path too long on Windows, keep below 240 characters : C:\Users\xxx\Downloads\geofire-java-master\geofire-java-master\examples\SFVehicles\SF Vehicles\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_text_dark_pressed.9.png

Error:Execution failed for task ':SF Vehicles:mergeDebugResources'.
> C:\Users\xxx\Downloads\geofire-java-master\geofire-java-master\examples\SFVehicles\SF Vehicles\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_text_dark_pressed.9.png: Error: File path too long on Windows, keep below 240 characters : C:\Users\xxx\Downloads\geofire-java-master\geofire-java-master\examples\SFVehicles\SF Vehicles\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_text_dark_pressed.9.png

**Comment by vanniktech** [comment]
Does not seem like there's much to fix here. Also, play services 9.0.2 is super old. Try updating it.

**Comment by samtstern** [comment]
Closing this issue since it's pretty old and the error does not have any obvious relation to geofire.
