### ISSUE TITLE
Multiple Databasereference

### ISSUE THREAD

**Issue by inromualdo** [firebase/geofire-java#73]
Can i use geoFire with multiple Databasereference at same time

**Comment by moseskarunia** [comment]
Afaik, no. 1 geofire instance is tied only to 1 database reference.

**Comment by vanniktech** [comment]
We have 3 references that we use and hence we're using 3 GeoFire instances and it works fine so far.

Using multiple references together is not supported.

**Comment by samtstern** [comment]
@inromualdo as the other comments said this is not currently supported.
