### ISSUE TITLE
how to make marker clickable? (Question)

### ISSUE THREAD

**Issue by aryayudha** [firebase/geofire-java#80]
Hi, i want to ask how to make marker from geofire maps clickable to reference some data from firebase realtime database ? (e.g i want see detail data from marker "A". Detail data are stored in firebase database). Thanks

**Comment by brezinajn** [comment]
You can use same key for your geofire and entity data (you **should** use same key :)) and save it to ```marker.tag```. Then on marker click fetch entity data. Or you can store your geofire data with your entity data. Takes some manual work, but works well.

**Comment by vanniktech** [comment]
This was answered and can be closed, right?
