### ISSUE TITLE
Download overhead costs associated with firing GeoQuery once

### ISSUE THREAD

**Issue by ShashankAnantharam** [firebase/geofire-java#81]
The question I have is posted here in detail: 
https://stackoverflow.com/questions/46896628/data-downloading-cost-of-geofire-geoquery 

Summary: If I fire Geoquery once every 3 seconds, will all the keys satisfying the query be downloaded by the mobile in bulk?? or will it come as seperate downloads. 
The reason I ask this is to minimize overhead costs for download. For example, 

if two users (A & B) satisfy a GeoQuery (i.e they are within a certain radius of me), 
then 
instead of using the onKeyMoved function to download the updates of A or of B individually, isn't it better to only have a GeoQuery download the locations of both A & B initially, then disable it and restart the same query after every 3 seconds or so?? 
The idea I have in mind is that by clubbing A & B together in the download, I will be able to reduce my total download overhead cost. 
But I may be wrong and that is why I want to know whether I am justified in using this approach and whether there are any better approaches for reducing download overhead costs associated with GeoQueries.

**Comment by vanniktech** [comment]
Have you tried analyzing this and using the Android Studio Performance Tools in 3.0.0?

**Comment by vanniktech** [comment]
Should we close this since it's inactive? If we ever run into this again we can create a new issue and put some more effort / dedication into this.

**Comment by ShashankAnantharam** [comment]
Yeah. Please close it.
