### ISSUE TITLE
Dependency on play-services or firebase 11.4.2+ breaks the build

### ISSUE THREAD

**Issue by samtstern** [firebase/geofire-java#82]
There are some new dependencies like `com.google.android.gms:play-services-tasks-license` that appear to be `aar` files but do not contain a `jar` within, only some txt and xml files.  This breaks the build as the javadoc plugin (and possibly other things) expect at least an empty jar.

**Comment by vanniktech** [comment]
Might this also be the reason that `2.1.3` was not released properly?

**Comment by samtstern** [comment]
Can you explain what you mean by "not released properly"?  I thought the
release succeeded.

**Comment by vanniktech** [comment]
The latest version on mavenCentral is [2.1.1](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.firebase%22%20AND%20a%3A%22geofire-android%22). I can't seem to find 2.1.3

**Comment by samtstern** [comment]
@vanniktech thanks for the heads up!  I have now properly released `2.1.3`.  `2.1.2` is not going to happen though, releasing an old version safely is sort of a pain.  That's my fault.

**Comment by vanniktech** [comment]
Thanks for fixing this. I'm able to get 2.1.3

**Comment by vanniktech** [comment]
Consuming geofire-java itself (the built version, 2.1.3) and Firebase 11.6.0 play together nicely for me. Is this just an internal bug but is resolved when consuming the built aar/jar?

**Comment by samtstern** [comment]
Yeah they play nice together but I can't actually build a version of geofire that has 11.6.0 as its stated dependency because of something maven tries to do in the releasing step.

I've filed a bug internally to work on this.

**Comment by vanniktech** [comment]
Also, the firebase ui auth library does not play well with 11.6.0.

**Comment by samtstern** [comment]
@vanniktech huh that's not good, I am also the maintainer of that library can you file an issue over there about the problems you're seeing?

**Comment by vanniktech** [comment]
There you go - https://github.com/firebase/FirebaseUI-Android/issues/1033

**Comment by vanniktech** [comment]
Given the Firebase-UI thing was easily fixed is this as easy to fix too?

**Comment by samtstern** [comment]
@vanniktech this comes from the fact that Play Services publishes some `-license` dependencies like `play-services-tasks-license` that are not really valid AARs, depending on who you ask, because they contain no code.  So Maven freaks out at the lack of a `jar` to read.

This could be fixed two ways:

- Play services builds an empty JAR for those dependencies
- We move to gradle, which does not care about the lack of a JAR

**Comment by vanniktech** [comment]
Then let's close this and link it in #102 to make sure this is not getting left out.

**Comment by samtstern** [comment]
This was fixed recently, I think, so going to tackle it.

**Comment by vanniktech** [comment]
Awesome.

**Comment by samtstern** [comment]
Fixed in `2.3.1`
