### ISSUE TITLE
Finding closest marker in Geoquery

### ISSUE THREAD

**Issue by joemerritt** [firebase/geofire-java#85]
Hi All, is there a way to find the closest marker in a geoquery? Ideally if someone was a long way off on the map they could compare their current location with all locations and go their directly.

Thank you for your time

**Comment by vanniktech** [comment]
Can't you just query again with a bigger radius then? Also it's quite easy to calculate how far certain coordinates are away. In your case the current location and the marker or two markers next to each other.

**Comment by samtstern** [comment]
@joemerritt there's no "built-in" way to do this, you need to iterate through all of the locations returned and compare their distance to the user's current location.

You can use the `GeoUtils.distance(...)` method to calculate the distance between two points.
