### ISSUE TITLE
Delta updates accross listeners

### ISSUE THREAD

**Issue by vanniktech** [firebase/geofire-java#88]
Use case:
We have a map, where we show pois and every time the camera changes we'll query for the given coordinates and radius. We use RxJava heavily and basically have an `Observable<CameraDirection>` that uses the CameraIdleListener under the hood. We use that Observable and [`switchMap`](http://reactivex.io/documentation/operators/switch.html) it with an `Observable<Poi>`, which uses Geofire under the hood.

Problem:
Currently, if you add a listener and remove it you start all over again (since it's calling the reset method). The behavior we want is that between listeners we'll only get the delta updates.

Current behavior:
addListener() -> onKeyEntered("A")
removeListener()
addListener() -> onKeyEntered("A")

Wanted behavior:
addListener() -> onKeyEntered("A")
removeListener()
addListener() -> Nothing

The delta updates behavior would allow us to easily create a new Observable each time for a given query and add the listener and when the Observable gets disposed, we can remove the listener. You can in fact already do this now, but then for every new Observable you'll get all of the add events already that you got before and basically end up with duplicated data.

Current workaround:
Only register one listener and emit Geofire changes through a Subject and use the `setLocation` method.

**Comment by vanniktech** [comment]
I've had an idea for this. We might be able to get away with this by implementing some kind of 'cache' that basically stores all of the `add` events that we've seen already and for a new listener we can just not emit them. It's likely that there are some corner cases though and there's more that we need to think about.

**Comment by samtstern** [comment]
@vanniktech to me this seems like something that a consumer would do on top of GeoFire, rather than something we need to build into the core library.

If we keep a cache we need to worry about memory usage and a cache eviction policy, which could be tricky.

**Comment by vanniktech** [comment]
The reason I'd want this to be in the library is so that some listeners could be unregistered. We don't get access to those from outside.

**Comment by vanniktech** [comment]
Internalized it.
