### ISSUE TITLE
Add CI for PRs

### ISSUE THREAD

**Issue by vanniktech** [firebase/geofire-java#91]
Let's add CI for PRs that will build the project so we'll see whether PR are green or not. I'd go for Travis CI or Circle Ci.

**Comment by vanniktech** [comment]
We'll probably need to find a good solution for `service-account.json (No such file or directory)`. Maybe a public project that's empty and everyone has access too?

**Comment by samtstern** [comment]
@vanniktech this is a great idea, and probably worth doing before we get too much deeper in all of the improvements you're suggesting.  

I'll take this one on.

**Comment by samtstern** [comment]
Closed via #98
