### ISSUE TITLE
AutoValue for GeoLocation, GeoHash, GeoHashQuery

### ISSUE THREAD

**Issue by vanniktech** [firebase/geofire-java#99]
Should we transform those 3 classes into AutoValue classes where equals / hashCode and toString will be implemented for us?

The advantage is that we'll get those things out of the box.

Instead of using the public constructors for creating them we could use builders (if really necessary, but I don't think it'll be) or factory methods (which would perform those checks then).

Depending if consumers rely on the public constructor this might be a breaking change. Also if we rename the methods it might be breaking too.

**Comment by samtstern** [comment]
What benefits would this bring besides being able to drop some of those boilerplate methods (`equals`, `hashCode`, `toString`, etc)?  I am hesitant to make this change / bring in a new build dependency if things are working alright as-is.  But open to it if you see other benefits.

**Comment by vanniktech** [comment]
Immutability too. There's no information leaked for consumers. The annotations are `compileOnly` scope and the annotation processor will generate the implementations for us. And those are shipped together with the jar/aar.

**Comment by samtstern** [comment]
Ok cool.  I am open to this if we can find a way to do it in a non-breaking way, otherwise it's probably not worth the churn.  I suspect there are many devs relying on the public constructors, especially for testing.

**Comment by vanniktech** [comment]
On second thought, probably not worth the effort unless we do a 3.0 which does not seem to be the plan. If we do, I'll keep this in mind. We can't add auto value and be backwards compatible since the constructors would turn into factory methods and hence closing this.

**Comment by samtstern** [comment]
@vanniktech thanks for the follow up.
